PatientRecordR1/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')),

    #patient html urls
    path('', include('patient.urls')),

    #patient rest urls
    path('api/', include('patient.api.urls'), name='patient_api'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patient/api/urls.py
from django.urls import path, re_path, include

from . import views
from .views import GoogleSocialAuthView

app_name = 'patient'

urlpatterns = [
    re_path(r'^patient/listjsn/$', views.api_patient_list, name = 'patientlistjason'),
    re_path(r'^patient/updatejsn/(?P<patient_id>[0-9]+)$', views.api_patient_update, name = 'patientupdatejason'),
    re_path(r'^patient/deletejsn/(?P<patient_id>[0-9]+)$', views.api_patient_delete, name = 'patientdeletejason'),
    re_path(r'^patient/addjsn$', views.api_patient_create, name = 'patientcreatejason'),
    re_path(r'^patient/register$', views.api_register_user, name = 'patientregisterjason'),
    re_path(r'^patient/rest-auth/', include('rest_auth.urls')),
    re_path(r'^patient/listjsnpage$', views.api_patient_list_page.as_view(), name='patientlistpage'),
    re_path(r'^patient/google/', GoogleSocialAuthView.as_view()),
    
]

patient/urls.py
from django.conf.urls import url
from django.urls import include

from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'patient'

urlpatterns = [
    
    url(r'^accounts/', include('allauth.urls')),
    #/
    url(r'^$', views.index, name='index'),

    #/register/
    url(r'^register/$', views.register_page, name='register'),

    #/login/
    url(r'^login/$', views.login_page, name='login'),

    #/logout/
    url(r'^logout/$', views.logout_user, name='logout'),

    #/patient/
    url(r'^patient/$', views.patientview, name='patientview'),

    #/patient/listjsn
    #url(r'^patient/listjsn/$', views.PatientList.as_view(), name='patientlistjason'),

    #/patient/1/
    url(r'^patient/(?P<patient_id>[0-9]+)/$', views.parientdetails, name='parientdetails'),

    #patient/add/
    url(r'patient/add/$', views.PatientCreate.as_view(), name='patient-add'),
]

patient/models.py
from django.db import models
from django.urls import reverse
from django import forms

from django.contrib.auth.models import User

from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

import mysql.connector

# Create your models here.
class Patient(models.Model):

    mysql_connection = mysql.connector.connect(host="localhost", user="root", passwd="Kolkata@1", database="patient_record_rest")

    if mysql_connection.is_connected():
        transaction = mysql_connection.cursor()
        transaction.execute(" select Transaction_display_name from Transaction where Transaction_name ='{}' and Lang_code = {} ".format('patient_fname', 1, ))
        patient_fname_verbose = str(transaction.fetchone()[0])

    patient_fname = models.CharField(max_length=255, verbose_name=patient_fname_verbose)
    patient_lname = models.CharField(max_length=255, verbose_name="Last Name")
    age = models.FloatField(verbose_name="Age of Patient")
    #gender = models.CharField(max_length=1, verbose_name="Gender")
    TYPE_SELECT = (('F', 'Female'),('M', 'Male'),)
    gender = models.CharField(max_length=11,choices=TYPE_SELECT)
    #gender = forms.ChoiceField(widget=forms.RadioSelect)
    ailment = models.CharField(max_length=1000, verbose_name="Ailment")
    patient_report = models.FileField(blank=True)
    patient_report_img = models.ImageField(blank=True, null=True)
    patient_report_raw = models.BinaryField(blank=True, null=True, editable=True)

    def get_absolute_url(self):
        return reverse('patient:patientview')  #, kwargs={'pk': self.pk})

    def __str__(self):
        return self.patient_fname + " : " + self.ailment

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_token_authorization(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

patient/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms



class UserRegistration(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']
        #field_classes = {'username': UsernameField}
        widgets = {
            'first_name': forms.fields.TextInput(attrs={'placeholder': 'First name...'}),
            'last_name': forms.fields.TextInput(attrs={'placeholder': 'Last name...'}),
            'username': forms.fields.TextInput(attrs={'placeholder': 'Username...'}),
            'email': forms.fields.TextInput(attrs={'placeholder': 'Email...'}),
            #'password1': forms.fields.TextInput(attrs={'placeholder': 'Enter password...'}),
            #'password2': forms.fields.TextInput(attrs={'placeholder': 'Confirm password...'}),
        }

        def __init__(self, *args, **kwargs):
            super(UserRegistration, self).__init__(*args, **kwargs)
            self.fields['password1'].widget = forms.PasswordInput(attrs={'placeholder': _("Password...")})
            self.fields['password2'].widget = forms.PasswordInput(attrs={'placeholder': _("Password...")})

patient/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.views import APIView

from rest_framework.permissions import IsAuthenticated, AllowAny

from rest_framework.authtoken.models import Token
from rest_framework.authentication import TokenAuthentication

from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView, GenericAPIView

from rest_framework.filters import SearchFilter, OrderingFilter

from patient.models import Patient

from .serializer import PatientSerializer, RegisterUserSerializer, GoogleSocialAuthSerializer


#Display all patient records or create a new patient record
'''
class PatientList(APIView):

    def get(self, request):
        patient = Patient.objects.all()
        serializer = PatientSerializer(patient, many=True)
        return Response(serializer.data)
'''

@api_view(['POST',])
@permission_classes((AllowAny,))
def api_register_user(request):

    if request.method == 'POST':
        serializer = RegisterUserSerializer(data=request.data)
        data = {}
        if serializer.is_valid():
            user = serializer.save()
            data['response'] = "New patient registered! "
            data['username'] = user.username
            data['first name'] = user.first_name
            data['last name'] = user.last_name
            data['email'] = user.email
            data['token'] = Token.objects.get(user=user).key
        else:
            data = serializer.errors
        return Response(data)

#view all
@api_view(['GET',])
@permission_classes((IsAuthenticated,))
def api_patient_list(request):
    try:
        patient = Patient.objects.all()
    except Patient.DoesNotExist:
        return Response(status.HTTP_404_NOT_FOUND) 

    if request.method == 'GET':
        serializer = PatientSerializer(patient, many=True)
        return Response(serializer.data)

#Google Auth
class GoogleSocialAuthView(GenericAPIView):
    serializer_class = GoogleSocialAuthSerializer

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = ((serializer.validated_data)['auth_token'])
        return Response(data, status=status.HTTP_200_OK)

#search-view all page wise
class api_patient_list_page(ListAPIView):
    queryset = Patient.objects.all()
    serializer_class = PatientSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    pagination_class = PageNumberPagination
    filter_backends = (SearchFilter, OrderingFilter)
    search_fields = ('patient_fname', 'patient_lname', 'ailment',)


#updare one
@api_view(['PUT',])
@permission_classes((IsAuthenticated,))
def api_patient_update(request, patient_id):
    try:
        patient = Patient.objects.get(pk = patient_id)
    except Patient.DoesNotExist:
        return Response(status.HTTP_404_NOT_FOUND) 

    user = request.user

    if patient.user != user:
        return Response('response', 'You dont have access to this page!!! ')

    if request.method == 'PUT':
        serializer = PatientSerializer(patient, data=request.data)
        data = {}
        if serializer.is_valid():
            serializer.save()
            data["success"] = "updated successfully!!!"
            return Response(data=data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

#delete one
@api_view(['DELETE',])
@permission_classes((IsAuthenticated,))
def api_patient_delete(request, patient_id):
    try:
        patient = Patient.objects.get(pk = patient_id)
    except Patient.DoesNotExist:
        return Response(status.HTTP_404_NOT_FOUND) 

    if request.method == 'DELETE':
        operation = patient.delete()
        data = {}
        if operation:
            data["success"] = "deleted successfully!!!"
        else:
            data["error"] = "delete failed!!!"
        return Response(data=data)

#create one
@api_view(['POST',])
@permission_classes((IsAuthenticated,))
def api_patient_create(request):
    #user = User.objects.get(pk=1)

    patient = Patient()

    if request.method == 'POST':
        serializer = PatientSerializer(patient, data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

patient/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.template import loader
from django.http import Http404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.utils.decorators import method_decorator




from .models import Patient
from .forms import UserRegistration



# Create your views here.
def register_page(request):
    form = UserRegistration

    if request.method == 'POST':
        form = UserRegistration(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('first_name')
            messages.success(request, 'Patient ' + user + ' registered succesfully!') 
            return redirect('patient:login')

    context = {'form' : form}
    return render(request, 'patient/register.html', context)

def login_page(request):
    if request.method == 'POST':
        uname = request.POST.get('username')
        pwd = request.POST.get('password')

        user = authenticate(request, username=uname, password=pwd)

        if user is not None:
            login(request, user)
            return redirect('patient:index')
        else:
            messages.info(request, 'Username or password is incorrect')

    return render(request, 'patient/login.html')

def logout_user(request):
    logout(request)
    return redirect('patient:login')

@login_required(login_url = 'patient:login')
def index(request):
    return render(request, 'patient/index.html')


@login_required(login_url = 'patient:login')
def patientview(request):
    patients = Patient.objects.all()
    #template = loader.get_template('patient/patient_view.html.html')
    context = {'patients' : patients,}
    #return HttpResponse(template.render(context, request))
    return render(request, 'patient/patient_view.html', context)

@login_required(login_url = 'patient:login')
def parientdetails(request, patient_id):
    patient = get_object_or_404(Patient, id=patient_id)
    return render(request, 'patient/patientdetails.html', {'patient' : patient})

@method_decorator(login_required, name='dispatch')
class PatientCreate(CreateView):
    model = Patient
    fields = ['patient_fname' , 'patient_lname' , 'age', 'gender', 'ailment', 'patient_report', 'patient_report_img', 'patient_report_raw']    

patient/templates/patient/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PatientRecord</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'patient/style/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">MedRec</a>
            </div>
    
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="/patient/add/">Register</a></li>
                <li><a href="/patient/">List</a></li>
            </ul>

            <form class="navbar-form navbar-right" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search...">
                </div>
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </form>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Hi... {{ request.user }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'patient:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>


        </div>
    </nav>

    {% block body %}
    {% endblock %}
    
</body>
</html>

patient/templates/patient/form-template.html
{% for field in form %}
    <div class="form-group">
        <!--<label class="control-lable col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>-->
        <label class="control-lable col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

patient/templates/patient/index.html
{% extends 'patient/base.html' %}
{% block body %}
    <h1>Welcome to Patient Records...</h1>
{% endblock %}

patient/templates/patient/login.html
{% load socialaccount %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			/*background: #7abecc !important; */
            background: #e8eeee;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #07525c !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		.btn-google {
    		color: #545454;
    		background-color: #ffffff;
    		box-shadow: 0 1px 2px 1px #ddd
		}

		.or-container {
			align-items: center;
			color: rgb(68, 60, 60);
			display: flex;
			margin: 25px 0
		}

		.line-separator {
			background-color: rgb(68, 60, 60);;
			flex-grow: 5;
			height: 1px
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
							<div class="or-container">
                                <div class="line-separator"></div>
                                <div class="or-label">OR</div>
                                <div class="line-separator"></div>
                            </div>
							<div class="row">
                                <div class="col-md-12"> 
									<a class="btn btn-lg btn-google btn-block text-uppercase btn-outline" href="{% provider_login_url 'google' %}"><img src="https://img.icons8.com/color/16/000000/google-logo.png"> Signup Using Google</a> 
								</div>
                            </div>
							   
					</form>

				</div>

                {% for msg in messages %}
                    <p id="messages">{{ msg }}</p>
                {% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'patient:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

patient/templates/patient/patient_form.html
{% extends 'patient/base.html' %}
{% block body %}

    <div class="registration-form">
        <div class="d-flex justify-content-center">
            <div class="user_card">
            <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'patient/form-template.html' %}
                <div class="form-group">
                    <div class="btn-group col-sm-offset-2 col-sm-offset-10">
                        <!--<div class="col-sm-offset-2 col-sm-offset-10">-->
                            <button type="submit" class="btn btn-default">Submit!!!</button>
                        <!--</div>-->
                        <!--<div class="col-sm-offset-2 col-sm-offset-10">-->
                            <button type="reset" class="btn btn-default">Clear!!!</button>
                        <!--</div>-->
                    </div>
                </div>
            </div>
            </form>
        </div> 
    </div>

{% endblock %}

patient/templates/patient/patient_view.html
{% extends 'patient/base.html' %}
{% block body %}

    <div  class="row">
        {% if patients %}
        
            {%for patient in patients  %}           
                <div class="col-sm-6 col-md-4">
                    <div class="card-body">
                        <div class="box">
                            <h3>{{patient.patient_fname}}</h3>
                            <div class="container">
                                <div class="row buttonBox">
                                    <a href="#" class="btn btn-primary a-btn-slide-text btn-xs">
                                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                        <span><strong>Add</strong></span>            
                                    </a>
                                    <a href="#" class="btn btn-primary a-btn-slide-text btn-xs">
                                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                        <span><strong>Edit</strong></span>            
                                    </a>
                                    <a href="{{patient.id}}" class="btn btn-primary a-btn-slide-text btn-xs">
                                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                        <span><strong>View</strong></span>            
                                    </a>
                                    <a href="#" class="btn btn-primary a-btn-slide-text btn-xs">
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                        <span><strong>Delete</strong></span>            
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>           
            {%endfor%}
            
        {% else %}
            <h2>No patient record available!!!</h2>
        {% endif %}
    </div>
{% endblock %}

patient/templates/patient/patientdetails.html
{% extends 'patient/base.html' %}
{% block body %}
    <div>
        <h3>Patient Name: {{patient.patient_fname}}
        {% if patient.patient_report_img %}
            <div style="float: right; margin-right: 2%;">
                <img src="{{patient.patient_report_img.url}}" alt="Patient image" width="100" height="100">
            </div>
        {% endif %}
        </h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Ailment</th>
                    <th>Age</th>
                    <th>Report</th>
                    <th>Size</th>
                    <th>Download</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{patient.ailment}}</td>
                    <td>{{patient.age}}</td>
                    {% if patient.patient_report %}
                        <td>{{patient.patient_report.name}}</td>
                        <td>{{patient.patient_report.size}}</td>
                        <td><a href="{{patient.patient_report.url}}" target="_blank">Reports</a></td>
                    {% else %}
                        <td>Not Available</td>
                        <td>Not Available</td>
                        <td>Not Available</td>
                    {% endif %}
                </tr>
            </tbody>

        </table>
    </div>
{% endblock %}

patient/templates/patient/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			/*background: #7abecc !important;*/
            background-color: #e8eeee;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #07525c !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-address-card"></i></span>
							</div>
							{{ form.first_name }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="far fa-address-card"></i></span>
							</div>
							{{ form.last_name }}
						</div>
                        <div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.username }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{ form.email }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password1 }}
						</div>
                        <div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2 }}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'patient:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>